In [1]:
from pathlib import Path

import pandas as pd

## Metadata

In [ ]:
df_meta = pd.read_csv(
    Path("../GSE88907.SraRunTable.csv"),
    index_col=0
)
df_meta.head()

,Assay Type,AvgSpotLen,Bases,BioProject,BioSample,Bytes,Center Name,chip_antibody,Consent,DATASTORE filetype,...,LibrarySelection,LibrarySource,Organism,Platform,ReleaseDate,create_date,version,Sample Name,source_name,SRA Study
Run,,,,,,,,,,,,,,,,,,,,,
SRR4430537,ChIP-Seq,200,2916988600,PRJNA349052,SAMN05919209,1760908342,GEO,AtCENH3 (Steve Henikoff lab),public,"fastq,run.zq,sra",...,ChIP,GENOMIC,Arabidopsis thaliana,ILLUMINA,2016-10-20T00:00:00Z,2016-10-18T17:56:00Z,1,GSM2354111,Wild-type A. thaliana Col seedlings,SRP091720
SRR4430539,ChIP-Seq,200,3916567800,PRJNA349052,SAMN05919197,2372959532,GEO,AtCENH3 (Steve Henikoff lab),public,"fastq,run.zq,sra",...,ChIP,GENOMIC,Arabidopsis thaliana,ILLUMINA,2016-10-20T00:00:00Z,2016-10-18T17:59:00Z,1,GSM2354114,Wild-type A. thaliana Col seedlings,SRP091720
SRR4430541,ChIP-Seq,200,3068504600,PRJNA349052,SAMN05919181,1899661337,GEO,AtCENH3 (Steve Henikoff lab),public,"fastq,run.zq,sra",...,ChIP,GENOMIC,Arabidopsis thaliana,ILLUMINA,2016-10-20T00:00:00Z,2016-10-18T17:56:00Z,1,GSM2354116,A. thaliana cenh3-1/cenh3-1LoCENH3 seedlings,SRP091720
SRR4430543,ChIP-Seq,200,7818682000,PRJNA349052,SAMN05919172,2860908696,GEO,LoCENH3 (this study),public,"fastq,run.zq,sra",...,ChIP,GENOMIC,Arabidopsis thaliana,ILLUMINA,2016-10-20T00:00:00Z,2016-10-18T18:06:00Z,1,GSM2354119,A. thaliana cenh3-1/cenh3-1LoCENH3 seedlings,SRP091720
SRR4430545,ChIP-Seq,200,8141244600,PRJNA349052,SAMN05919163,2984673616,GEO,LoCENH3 (this study),public,"fastq,run.zq,sra",...,ChIP,GENOMIC,Arabidopsis thaliana,ILLUMINA,2016-10-20T00:00:00Z,2016-10-18T18:06:00Z,1,GSM2354121,A. thaliana cenh3-1/cenh3-1LoCENH3 seedlings,SRP091720

In [4]:
df_meta["chip_antibody"].value_counts()

chip_antibody
AtCENH3 (Steve Henikoff lab)    3
LoCENH3 (this study)            3
ZmCENH3 (Kelly Dawe lab)        3
none                            2
Name: count, dtype: int64

In [6]:
df_meta_filtered = df_meta[df_meta["chip_antibody"].isin(["AtCENH3 (Steve Henikoff lab)", "none"])]
df_meta_filtered

,Assay Type,AvgSpotLen,Bases,BioProject,BioSample,Bytes,Center Name,chip_antibody,Consent,DATASTORE filetype,...,LibrarySelection,LibrarySource,Organism,Platform,ReleaseDate,create_date,version,Sample Name,source_name,SRA Study
Run,,,,,,,,,,,,,,,,,,,,,
SRR4430537,ChIP-Seq,200,2916988600,PRJNA349052,SAMN05919209,1760908342,GEO,AtCENH3 (Steve Henikoff lab),public,"fastq,run.zq,sra",...,ChIP,GENOMIC,Arabidopsis thaliana,ILLUMINA,2016-10-20T00:00:00Z,2016-10-18T17:56:00Z,1,GSM2354111,Wild-type A. thaliana Col seedlings,SRP091720
SRR4430539,ChIP-Seq,200,3916567800,PRJNA349052,SAMN05919197,2372959532,GEO,AtCENH3 (Steve Henikoff lab),public,"fastq,run.zq,sra",...,ChIP,GENOMIC,Arabidopsis thaliana,ILLUMINA,2016-10-20T00:00:00Z,2016-10-18T17:59:00Z,1,GSM2354114,Wild-type A. thaliana Col seedlings,SRP091720
SRR4430541,ChIP-Seq,200,3068504600,PRJNA349052,SAMN05919181,1899661337,GEO,AtCENH3 (Steve Henikoff lab),public,"fastq,run.zq,sra",...,ChIP,GENOMIC,Arabidopsis thaliana,ILLUMINA,2016-10-20T00:00:00Z,2016-10-18T17:56:00Z,1,GSM2354116,A. thaliana cenh3-1/cenh3-1LoCENH3 seedlings,SRP091720
SRR4430555,ChIP-Seq,200,3819348200,PRJNA349052,SAMN05919072,2274409380,GEO,none,public,"fastq,run.zq,sra",...,ChIP,GENOMIC,Arabidopsis thaliana,ILLUMINA,2016-10-20T00:00:00Z,2016-10-18T17:57:00Z,1,GSM2354126,Wild-type A. thaliana Col seedlings,SRP091720
SRR4430557,ChIP-Seq,200,7390176000,PRJNA349052,SAMN05919056,2797303390,GEO,none,public,"fastq,run.zq,sra",...,ChIP,GENOMIC,Arabidopsis thaliana,ILLUMINA,2016-10-20T00:00:00Z,2016-10-18T18:12:00Z,1,GSM2354127,A. thaliana cenh3-1/cenh3-1LoCENH3 seedlings,SRP091720